CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "api_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"method" text NOT NULL,
	"endpoint" text NOT NULL,
	"status_code" integer NOT NULL,
	"duration" integer NOT NULL,
	"user_agent" text,
	"ip" text,
	"timestamp" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "bid_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bid_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" text NOT NULL,
	"rfq_contract_id" text NOT NULL,
	"lender" text NOT NULL,
	"interest_rate" real NOT NULL,
	"additional_terms" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "collateral_pool_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "collateral_pool_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" text NOT NULL,
	"pool_id" text NOT NULL,
	"borrower" text NOT NULL,
	"lender" text NOT NULL,
	"loan_id" text NOT NULL,
	"total_initial_value" real NOT NULL,
	"total_current_value" real NOT NULL,
	"loan_amount" real NOT NULL,
	"current_ltv" real NOT NULL,
	"status" text NOT NULL,
	"margin_call_active" boolean DEFAULT false NOT NULL,
	"last_valuation_time" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "collateral_pool_cache_contract_id_unique" UNIQUE("contract_id")
);
--> statement-breakpoint
CREATE TABLE "credit_profile_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "credit_profile_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" text NOT NULL,
	"party" text NOT NULL,
	"profile_id" text NOT NULL,
	"credit_score" integer NOT NULL,
	"risk_rating" text NOT NULL,
	"total_borrowed" real NOT NULL,
	"total_repaid" real NOT NULL,
	"current_outstanding" real NOT NULL,
	"number_of_loans" integer NOT NULL,
	"number_of_defaults" integer NOT NULL,
	"number_of_late_payments" integer NOT NULL,
	"last_updated" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "credit_profile_cache_contract_id_unique" UNIQUE("contract_id")
);
--> statement-breakpoint
CREATE TABLE "platform_analytics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "platform_analytics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"total_rfqs" integer DEFAULT 0 NOT NULL,
	"total_bids" integer DEFAULT 0 NOT NULL,
	"total_loans" integer DEFAULT 0 NOT NULL,
	"total_volume" real DEFAULT 0 NOT NULL,
	"total_collateral" real DEFAULT 0 NOT NULL,
	"total_yield_generated" real DEFAULT 0 NOT NULL,
	"active_users" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "platform_analytics_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "rfq_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfq_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" text NOT NULL,
	"borrower" text NOT NULL,
	"loan_amount" real NOT NULL,
	"collateral_amount" real NOT NULL,
	"collateral_asset" text NOT NULL,
	"loan_duration_days" integer NOT NULL,
	"interest_rate" real,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text NOT NULL,
	"expires_at" text NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "rfq_cache_contract_id_unique" UNIQUE("contract_id")
);
--> statement-breakpoint
CREATE TABLE "risk_assessment_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "risk_assessment_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" text NOT NULL,
	"assessment_id" text NOT NULL,
	"borrower" text NOT NULL,
	"lender" text NOT NULL,
	"loan_amount" real NOT NULL,
	"recommended_rate" real NOT NULL,
	"risk_adjusted_rate" real NOT NULL,
	"approval_recommendation" text NOT NULL,
	"assessment_date" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "risk_assessment_cache_contract_id_unique" UNIQUE("contract_id")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"value" text NOT NULL,
	"description" text,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "settings_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"daml_party" text,
	"role" text DEFAULT 'borrower' NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_daml_party_unique" UNIQUE("daml_party")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;